#!/usr/bin/env ruby

require 'work_timer'
require "io/console" # 改行なしで'q'を取得するのに必要

def setWork(myWorkObj)
  # 作業時間をリアルタイム表示
  myWorkObj.view
  myWorkObj.start_work
  # 'q'が入力されたら作業時間カウント終了
  while STDIN.getch != 'q'; end
  puts
  myWorkObj.end_work
end

if ARGV[0]
  # 作業記録を保存するログファイル
  fileName = ARGV[0]
  myWork = WorkTimer::Work.new(fileName)
  puts "quit : 'q'"
  puts "total: " + myWork.total_time
  setWork(myWork)
  puts "save : " + fileName
  myWork.record_time
  puts "total: " + myWork.total_time
else
  myWork = WorkTimer::Work.new("EMPTY")
  puts "quit : 'q'"
  setWork(myWork)
end
